// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revoke_refresh_token.sql

package database

import (
	"context"
	"time"
)

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET updated_at = $2,
revoked_at = $2
WHERE token=$1
`

type RevokeRefreshTokenParams struct {
	Token     string
	UpdatedAt time.Time
}

// plpgsql-language-server:disable
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.Token, arg.UpdatedAt)
	return err
}
