// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_users_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserChrirpyRed = `-- name: UpdateUserChrirpyRed :exec
UPDATE users
SET is_chirpy_red = $2
WHERE id=$1
`

type UpdateUserChrirpyRedParams struct {
	ID          uuid.UUID
	IsChirpyRed bool
}

// plpgsql-language-server:disable
func (q *Queries) UpdateUserChrirpyRed(ctx context.Context, arg UpdateUserChrirpyRedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserChrirpyRed, arg.ID, arg.IsChirpyRed)
	return err
}
