// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_refresh_token.sql

package database

import (
	"context"
	"time"
)

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE refresh_tokens
SET updated_at = $2
WHERE token=$1
`

type UpdateRefreshTokenParams struct {
	Token     string
	UpdatedAt time.Time
}

// plpgsql-language-server:disable
func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateRefreshToken, arg.Token, arg.UpdatedAt)
	return err
}
