// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_user_email_password.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE users
SET email = $2,
hashed_password = $3
WHERE id=$1

RETURNING id, created_at, updated_at, email, hashed_password
`

type UpdateUserDetailsParams struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
}

// plpgsql-language-server:disable
func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserDetails, arg.ID, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
